default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV["DOMAUTHORITY_DB_NAME_DEVELOPMENT"] %>
  username: <%= ENV["DOMAUTHORITY_DB_USERNAME_DEVELOPMENT"] %>
  password: <%= ENV["DOMAUTHORITY_DB_PASSWORD_DEVELOPMENT"] %>

test:
  <<: *default
  database: <%= ENV["DOMAUTHORITY_DB_NAME_TEST"] %>
  username: <%= ENV["DOMAUTHORITY_DB_USERNAME_TEST"] %>
  password: <%= ENV["DOMAUTHORITY_DB_PASSWORD_TEST"] %>

production:
  <<: *default
  database: <%= ENV["DOMAUTHORITY_DB_NAME_PRODUCTION"] %>
  username: <%= ENV["DOMAUTHORITY_DB_USERNAME_PRODUCTION"] %>
  password: <%= ENV["DOMAUTHORITY_DB_PASSWORD_PRODUCTION"] %>
